const express = require('express');
const pool = require('../db/pool');
const AccountantRepository = require('../repositories/accountant.repository');
const AccountantService = require('../services/accountant.service');
const createController = require('../controllers/accountant.controller');
const config = require('../config/env');
const telegramAuth = require('../middleware/telegram-auth');
const router = express.Router();
const controller = createController({ service: new AccountantService(new AccountantRepository(pool)) });
router.post('/', telegramAuth(config), controller.create);
router.get('/available', telegramAuth(config), controller.available);
module.exports = router;
