const express = require('express');
const pool = require('../db/pool');
const config = require('../config/env');
const ChatRepository = require('../repositories/chat.repository');
const ChatService = require('../services/chat.service');
const { createAIProvider } = require('../integrations/ai/provider');
const createController = require('../controllers/chat.controller');
const telegramAuth = require('../middleware/telegram-auth');
const router = express.Router();
const chatService = new ChatService({ chatRepository: new ChatRepository(pool), aiProvider: createAIProvider(config) });
const controller = createController({ chatService });
router.post('/message', telegramAuth(config), controller.send);
router.get('/history/:clientId', telegramAuth(config), controller.history);
module.exports = router;
