const express = require('express');
const pool = require('../db/pool');
const ClientRepository = require('../repositories/client.repository');
const ClientService = require('../services/client.service');
const createController = require('../controllers/client.controller');
const config = require('../config/env');
const telegramAuth = require('../middleware/telegram-auth');
const router = express.Router();
const controller = createController({ service: new ClientService(new ClientRepository(pool)) });
router.post('/', telegramAuth(config), controller.create);
router.get('/:telegramId', telegramAuth(config), controller.getByTelegramId);
module.exports = router;
