const express = require('express');
const pool = require('../db/pool');
const ClientRepository = require('../repositories/client.repository');
const IntegrationService = require('../services/integration.service');
const createController = require('../controllers/integration.controller');
const config = require('../config/env');
const telegramAuth = require('../middleware/telegram-auth');
const router = express.Router();
const controller = createController({ service: new IntegrationService(new ClientRepository(pool)) });
router.post('/1c', telegramAuth(config), controller.set1C);
module.exports = router;
